### PR TITLE
Update AngularFire v7 & Firebase v9

### LINKED ISSUE #205: Firebase 9 support
Firebase 9 is currently and beta and support tree shaking
Angularfire 7 (in beta) support Firebase 9 

it'd be lovely to be able to us akita-ng-fire and Firebase with tree shaking (even in beta, and most of the job would be done for the official release)

Thanks

### PR DESCRIPTION
**Pull request by randallmeeker**
I closed #217 and opened this one for simplicity/clarity sake. 

resolves #205

@GrandSchtroumpf

### CODE REVIEW

**Review by GrandSchtroumpf — APPROVED** [review]
LGTM

**Comment by hakimio** [comment]
@randallmeeker that's a very lazy approach to the upgrade. Using "compat" imports will not give us proper tree-shaking support - the most notable feature of Firebase v9.

**Comment by GrandSchtroumpf** [comment]
@hakimio Please avoid agressive language. @randallmeeker did spend time working on this update, there is nothing lazy about her/his work. Contributing to an open source project is not an easy task and should be supported instead of discouraged.
Other PRs to update the code to a newer version are welcome.

**Comment by hakimio** [comment]
@GrandSchtroumpf Ok, if no one else is taking this task, I'll look into doing proper upgrade sometime next week.

**Comment by GrandSchtroumpf** [comment]
@hakimio ok thanks. Can you write a comment on the issue to let the community knows about that : 
https://github.com/dappsnation/akita-ng-fire/issues/205

**Pull request merged**
