### PR TITLE
add path observable support

### PR DESCRIPTION
**Pull request by ex37**
At the moment you can't set  path observable, like stated in the docs:
https://netbasal.gitbook.io/akita/angular/firebase-integration/collection-service#path-observable

First of all this is a temporary fix to address the issue, I'll need your collaboration @GrandSchtroumpf  to continue.
Here are some of the problems to be solved:

- [ ] in case of having path observable you should be able to omit path parameter from `CollectionConfig`
- [ ] `currentPath` can in fact return a path snapshot, but as a promise. This can be helpful in `getValue` method, for example, as it's async anyway.
- [ ] other sync methods should also be updated to handle observable path
- [ ] probably we should have an ability to pass observable path directly to sync functions as a parameter
- [ ] not sure how `pathWithParams` method should be handled in case of observable path
- [ ] tests I guess...?

And yes, thanks for your work on this lib, I really like this abstraction on how can firebase be used with akita.

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
Hello, thanks for the PR. I'm actually thinking about deprecating observable path. This is **super difficult** to maintain and apply to all methods (`sync`, `add`, `remove`, `update`) and introduce a lot of exceptions.

I would instead recommend to use snapshot for write methods : 
```typescript
get currentPath() {
  return `movies/${this.movieQuery.getActiveId()}/stakeholders`
}
```
For sync methods you can use the `{ params }` options : 
```typescript
this.router.params.pipe(
  switchMap(params => this.syncCollection({ params })) // will find the params "movieId" and apply it to the path
).subscribe()
```

If this doesn't match your requirement, let me know so we can find other solutions.

**Comment by ex37** [comment]
the problem with this solution is, that in case there is no activeId at the moment you'll end up with `movies/null/stakeholders` path

**Comment by GrandSchtroumpf** [comment]
I'm not sure to see how using an observable would solve this problem.
You can add some logic in your getter, either by throwing an error or providing a fallback path.
We can also provide a `params` in the `WriteOptions` that would serve the same purpose as in the `SyncOptions`. Would it solve your issue ?

**Comment by ex37** [comment]
using modified code from PR I can write:
```
  get path() {
    return this.authQuery.select('uid').pipe(
      filter(uid => !!uid),
      map(uid => `user-organizations/${uid}/organizations`)
    );
  }
```

The reason I chose akita is cause it's heavily built on observables. I assume we can solve the problems I have with synchronous code solutions, but thats not really what I'd like to do :)

**Comment by ex37** [comment]
btw, any chance we can discuss this in slack / telegram or another IM?

**Comment by GrandSchtroumpf** [comment]
You can contact me on gitter : `https://gitter.im/grandschtroumpf`

**Pull request closed without merging**
